version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyerdb
      MYSQL_USER: foyeruser
      MYSQL_PASSWORD: foyerpass
    ports:
      - "3306:3306"
    networks:
      - tp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  tp-foyer-app:
    image: onsbz/tp-foyer:v5.0.19
    container_name: tp-foyer-container
    depends_on:
      mysql-db:
        condition: service_healthy
      otel-collector:
        condition: service_started
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/foyerdb
      SPRING_DATASOURCE_USERNAME: foyeruser
      SPRING_DATASOURCE_PASSWORD: foyerpass
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_SERVICE_NAME: tp-foyer
    networks:
      - tp-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector-container
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "8888:8888"
      - "8889:8889"
    networks:
      - tp-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - tp-network

  grafana:
    image: grafana/grafana
    container_name: grafana-container
    ports:
      - "3001:3000"
    networks:
      - tp-network

networks:
  tp-network:
    driver: bridge
